### PR TITLE
Respect the license.

### PR DESCRIPTION
**Pull request by ClaytonTDM**
https://github.com/ClaytonTDM/brave-search-thing

### CODE REVIEW

**Comment by actuallyarm64** [comment]
Sorry, but it seems like the code has been changed. Now don't go on my profile again, bub.

**Comment by ClaytonTDM** [comment]
lmao it hasnt

**Comment by ClaytonTDM** [comment]
bro 😭
image

**Comment by actuallyarm64** [comment]
go ahead, this search engine was a joke anyway

**Pull request closed without merging**
